# Travis CI Configuration File

# Use new Travis container-based infrastructure
# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

# Tell Travis CI we're using PHP
language: php

# Configure caches
cache:
  apt: true

# PHP version used in first build configuration.
php:
    - 7.1
    - 7.0
    - 5.6
    - 5.5
    - 5.4
    - 5.3
    - 5.2

# WordPress comes from the Git mirror, where 'master' mirrors svn 'trunk' and
# x.y mirrors the latest from the x.y branch
env:
    - WP_VERSION=master
    - WP_VERSION=4.7

# Build matrix options
matrix:
  include:
    - php: nightly
      env: WP_VERSION=master
    - php: hhvm
      env: WP_VERSION=master
      sudo: required
      dist: trusty
      group: edge
      addons:
        apt:
          packages:
            - mysql-server-5.6
            - mysql-client-core-5.6
            - mysql-client-5.6
  allow_failures:
    - php: nightly
    - php: hhvm
#  fast_finish: true

# before_install: Failures in this section will result in build status 'errored'
before_install:
    # setup WP_DEVELOP_DIR (needed for bbPress to bootstrap WP PHPUnit tests)
    - export WP_DEVELOP_DIR=/tmp/wordpress/
    - mkdir -p $WP_DEVELOP_DIR
    # clone the WordPress develop repo
    - git clone --depth=1 --branch="$WP_VERSION" git://develop.git.wordpress.org/ $WP_DEVELOP_DIR
    # clone the BuddyPress develop repo
    - git clone --depth=1 git://buddypress.git.wordpress.org/ $WP_DEVELOP_DIR/src/wp-content/plugins/buddypress
    - plugin_slug=$(basename $(pwd))
    - plugin_dir=$WP_DEVELOP_DIR/src/wp-content/plugins/$plugin_slug
    - cd ..
    - mv $plugin_slug $plugin_dir
    # set up tests config
    - cd $WP_DEVELOP_DIR
    - echo $WP_DEVELOP_DIR
    - cp wp-tests-config-sample.php wp-tests-config.php
    - sed -i "s/youremptytestdbnamehere/wordpress_test/" wp-tests-config.php
    - sed -i "s/yourusernamehere/root/" wp-tests-config.php
    - sed -i "s/yourpasswordhere//" wp-tests-config.php
    # set up database
    - mysql -e 'CREATE DATABASE wordpress_test;' -uroot
    # prepare for running the tests
    - cd $plugin_dir
    # setup NodeJS version using NVM
    - node --version
    - nvm install 4
    - node --version
    - npm install -g grunt-cli
    - npm --version
    - phpenv versions
    - mysql --version

# before_script: Failures in this section will result in build status 'failed'
before_script:
  - stable='^[0-9\.]+$'; if [[ "$TRAVIS_PHP_VERSION" =~ $stable ]]; then phpenv config-rm xdebug.ini; fi
  - npm install
  - grunt build

# Run tests
script:
  - grunt travis
  - if [ "$TRAVIS_PHP_VERSION" != "5.2" ]; then grunt test:buddypress; fi

notifications:
    email: false
    irc:
      channels:
        - secure: "eRufY5taFDAuASgf9kB8oIC58lK9jLCTGVZ9Dr4M3Xxnwsj6t42Z5U9ZJ5wWAa0+9rf3UwbXj32Nd4QVvKWQL+IYTolX+LHzIidjKjYhOoCNr9HoMgjNOrjozXezKqqXzYKkPdX6drxk7JkK+ftx8qvVtZgRU8BS9sjhYDWh1X4="
      template:
        - "Build %{build_number} (%{branch} - %{commit}): %{message} %{build_url}"
    slack:
        secure: mWDf/kxLOmmbkPC8z/pmiZOWmLRv+v/lOagiALI7gMGUBpAKbxwDIoQm/hxMYwLFNXS5/Fw0ARtaphL5ZBJZKXnRpZbDbkNcCxmPiyf9BHyMEJS9VpaTcfb+Nu7CzOdYa9GiAdfzAhwZ3d6Fn+5QQeAgZVLu0cr+WJTf1FKEX7w=
