# Travis CI Configuration File

# Use new Travis container-based infrastructure
# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

# Tell Travis CI we're using PHP
language: php

# PHP version used in first build configuration.
php:
    - 5.2
    - 5.3
    - 5.4
    - 5.5
    - 5.6

# WordPress comes from the Git mirror, where 'master' mirrors svn 'trunk' and
# x.y mirrors the latest from the x.y branch
env:
    - WP_VERSION=master
    - WP_VERSION=4.1
    - WP_VERSION=4.0
    - WP_VERSION=3.9
    - WP_VERSION=3.8
    - WP_VERSION=3.7

# Build matrix options
matrix:
  include:
    - php: 7.0
      env: WP_VERSION=master
    - php: hhvm
      env: WP_VERSION=master
    - php: hhvm-nightly
      env: WP_VERSION=master
  allow_failures:
    - php: 7.0
    - php: hhvm
    - php: hhvm-nightly
  fast_finish: true

# before_install: Failures in this section will result in build status 'errored'
before_install:
    # setup WP_DEVELOP_DIR (needed for bbPress to bootstrap WP PHPUnit tests)
    - export WP_DEVELOP_DIR=/tmp/wordpress/
    - mkdir -p $WP_DEVELOP_DIR
    # clone the WordPress develop repo
    - git clone --depth=1 --branch="$WP_VERSION" git://develop.git.wordpress.org/ $WP_DEVELOP_DIR
    # clone the BuddyPress develop repo
    - git clone --depth=1 git://buddypress.git.wordpress.org/ $WP_DEVELOP_DIR/src/wp-content/plugins/buddypress
    - plugin_slug=$(basename $(pwd))
    - plugin_dir=$WP_DEVELOP_DIR/src/wp-content/plugins/$plugin_slug
    - cd ..
    - mv $plugin_slug $plugin_dir
    # set up tests config
    - cd $WP_DEVELOP_DIR
    - echo $WP_DEVELOP_DIR
    - cp wp-tests-config-sample.php wp-tests-config.php
    - sed -i "s/youremptytestdbnamehere/wordpress_test/" wp-tests-config.php
    - sed -i "s/yourusernamehere/root/" wp-tests-config.php
    - sed -i "s/yourpasswordhere//" wp-tests-config.php
    # disable WP_DEBUG for PHP >= 5.5 due to ext/mysqli E_DEPRECATED errors
    - if [[ "$TRAVIS_PHP_VERSION" > 5.4* ]] && [[ "$WP_VERSION" == "3.7" ]] ; then sed -i "s:define( 'WP_DEBUG://define( 'WP_DEBUG:" wp-tests-config.php; fi;
    # set up database
    - mysql -e 'CREATE DATABASE wordpress_test;' -uroot
    # prepare for running the tests
    - cd $plugin_dir
    - npm install -g grunt-cli

# before_script: Failures in this section will result in build status 'failed'
before_script:
  - npm install
  - grunt build

# Run tests
script:
  - grunt travis

# Code Coverage
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
    email: false
    slack:
        secure: mWDf/kxLOmmbkPC8z/pmiZOWmLRv+v/lOagiALI7gMGUBpAKbxwDIoQm/hxMYwLFNXS5/Fw0ARtaphL5ZBJZKXnRpZbDbkNcCxmPiyf9BHyMEJS9VpaTcfb+Nu7CzOdYa9GiAdfzAhwZ3d6Fn+5QQeAgZVLu0cr+WJTf1FKEX7w=
